version: 0.0
os: linux
files:
        - source: /
          destination: /home/ubuntu/codepipeline/angularjs/

hooks:
        BeforeInstall:
                - location: Scripts/BeforeInstall.sh
                  timeout: 300
                  runas: root
        AfterInstall:
                - location: Scripts/Install.sh
                  timeout: 600
                  runas: root
